u8-zawa/HoloLens2Iot

README.md
=> :books:README を更新しました #10

README.md
=> :books:README.md を更新 #16

Assets/Scenes/GsrSensorScene.unity, Assets/Scenes/GsrSensorScene.unity.meta
=> GsrSensorScene を作成 #19

.gitignore, README.md
=> Feature/#38  update readme

Assets/Scenes/Co2SensorScene.unity, Assets/Scripts/CO2Scene.meta, Assets/Scripts/CO2Scene/FloatMove.cs, Assets/Scripts/CO2Scene/FloatMove.cs.meta
#34
CO2モデルの浮遊管理スクリプトと、漂うエリアを示す箱を作成
=> Feature/#34  floating co2

Assets/Scenes/MqttSampleScene.unity, Assets/Scripts/MqttController.cs, Assets/Scripts/Value.meta, Assets/Scripts/Value/SensorData.cs, Assets/Scripts/Value/SensorData.cs.meta, Assets/Scripts/Value/Statistics.cs, Assets/Scripts/Value/Statistics.cs.meta, UserSettings/EditorUserSettings.asset
=> Feature/#24  handle json

README.md
=> READMEの名前を変更　#42

Assets/Scenes/MqttSampleScene.unity, Assets/Scripts/MqttController.cs
#49
※ functionノード を sensorノード の代わりに使用しています
<details><summary>JSON（mqtt のサーバ設定がされてない状態）</summary>
```
[
{
"id": "f6a999a66f1db233",
"type": "mqtt out",
"z": "a5a8f9ecbad6767c",
"name": "",
"topic": "prmn_iot/co2",
"qos": "",
"retain": "",
"respTopic": "",
"contentType": "",
"userProps": "",
"correl": "",
"expiry": "",
"broker": "",
"x": 1270,
"y": 520,
"wires": []
},
{
"id": "dd943872a069788b",
"type": "inject",
"z": "a5a8f9ecbad6767c",
"name": "",
"props": [
{
"p": "payload"
},
{
"p": "topic",
"vt": "str"
}
],
"repeat": "",
"crontab": "",
"once": false,
"onceDelay": 0.1,
"topic": "",
"payload": "",
"payloadType": "date",
"x": 860,
"y": 520,
"wires": [
[
"67243a784a246669"
]
]
},
{
"id": "2480e5a5a713e8fd",
"type": "mqtt in",
"z": "a5a8f9ecbad6767c",
"name": "",
"topic": "prmn_iot/co2", …
```
=> Feature/#49  get sensor value

Assets/Prefabs/co2/co2.prefab, Assets/Scripts/CO2Scene/FloatMove.cs
#51
Spawnerから生成されたCO2モデルを掴めるようにした。
掴んで箱の外に持って行ける不具合があるが、それについては#52で対応する予定。
=> Feature/#51  grab co2

Assets/Prefabs/co2/co2.prefab, Assets/Scenes/Co2SensorScene.unity, Assets/Scripts/CO2Scene/FloatMove.cs, Assets/Scripts/CollisionDetector.cs, Assets/Scripts/CollisionDetector.cs.meta, ProjectSettings/TagManager.asset
CO2モデルが自動で箱内に戻るようにした。
CO2モデルを箱外まで運び、手を離すと初期位置に戻る。
=> Feature/#52  co2 out of wall

Assets/Scripts/CO2Scene/FloatMove.cs
#68
CO2モデルを掴んで大きさを変更してから手を離すと、モデルの大きさが元に戻ることを確認する。
=> Feature/#68  co2 model size fix

Assets/MixedRealityToolkit.Generated/CustomProfiles.meta, Assets/MixedRealityToolkit.Generated/CustomProfiles/HoloLens2IotMixedRealitySpatialAwarenessMeshObserverProfile.asset, Assets/MixedRealityToolkit.Generated/CustomProfiles/HoloLens2IotMixedRealitySpatialAwarenessMeshObserverProfile.asset.meta, Assets/MixedRealityToolkit.Generated/CustomProfiles/HoloLens2IotMixedRealitySpatialAwarenessSystemProfile.asset, Assets/MixedRealityToolkit.Generated/CustomProfiles/HoloLens2IotMixedRealitySpatialAwarenessSystemProfile.asset.meta, Assets/MixedRealityToolkit.Generated/CustomProfiles/HoloLens2IotMixedRealityToolkitConfigurationProfile.asset, Assets/MixedRealityToolkit.Generated/CustomProfiles/HoloLens2IotMixedRealityToolkitConfigurationProfile.asset.meta, Assets/MixedRealityToolkit.Generated/ProjectPreferences.asset, Assets/Scenes/Co2SensorScene.unity, Assets/Scenes/GsrSensorScene.unity, Assets/Scenes/MqttSampleScene.unity, Assets/Scenes/SampleScene.unity, Assets/Scenes/UdSensorScene.unity
=> 全てのシーンで空間メッシュを非表示にした

Assets/Scenes/UdSensorScene.unity, Assets/Scripts/UDScene.meta, Assets/Scripts/UDScene/ThresholdJudge.cs, Assets/Scripts/UDScene/ThresholdJudge.cs.meta
#67
- UdSensorSceneで超音波距離センサーから取得した値が閾値以上か以下かを判定できるようになった
=> Feature/#67  threshold judgment

Assets/Prefabs/co2/co2.prefab
#73
CO2シーンにあるCO2モデルを掴んだ時のエフェクトを追加しました。
- 音が鳴る
- ToolTipが表示される
=> Feature/#73  add grab effect

Assets/Scripts/CO2Scene/GraphRender.cs, Assets/Scripts/CO2Scene/Spawner.cs, Assets/Scripts/CO2Scene/UI/CO2InfoTextUI.cs, Assets/Scripts/Common/SensorDataManager.cs, Assets/Scripts/MqttController.cs, Assets/Scripts/UDScene/ThresholdJudge.cs, Assets/Scripts/Value/SensorData.cs, Assets/Scripts/Value/Statistics.cs
#85 
- {"error": "Node is offline"}というメッセージを受け取った際、データを格納しないようにする。
Jsonメッセージの内、"name"が空であるものは格納が拒否されるため、エラーが出ません。
恐らく誰かのNode-redが起動されていて、そっちのメッセージを受信したのだと思われる。
=> nullあるいはnameがnullのデータは受け付けないようにした

Assets/Prefabs/Dialog.meta, Assets/Prefabs/Dialog/DialogLarge_192x192.prefab, Assets/Prefabs/Dialog/DialogLarge_192x192.prefab.meta, Assets/Prefabs/Dialog/DialogMedium_192x128.prefab, Assets/Prefabs/Dialog/DialogMedium_192x128.prefab.meta, Assets/Prefabs/Dialog/DialogSmall_192x96.prefab, Assets/Prefabs/Dialog/DialogSmall_192x96.prefab.meta, Assets/Prefabs/PressableRoundButton.prefab, Assets/Prefabs/PressableRoundButton.prefab.meta, Assets/Scenes/SampleScene.unity, Assets/Scripts/Common/DialogController.cs, Assets/Scripts/Common/DialogController.cs.meta
#80
GsrSensorSceneで使用するであろうダイアログを表示することが出来る機能を追加。
サンプルはSampleSceneに設置してある。
=> Feature/#80  add dialog prefabs

Assets/Scenes/UdSensorScene.unity, Assets/Scripts/UDScene/ThresholdJudge.cs, Assets/Scripts/UDScene/ThresholdJudgeUI.cs, Assets/Scripts/UDScene/ThresholdJudgeUI.cs.meta
#90 
閾値判定の結果によってテキストの表示を切り替えられるようにした。
=> 判定結果によってテキストの表示を切り替えられるようにした

Assets/Scripts/CO2Scene/GraphRender.cs, Assets/Scripts/CO2Scene/Spawner.cs, Assets/Scripts/CO2Scene/UI/CO2InfoTextUI.cs, Assets/Scripts/UDScene/ThresholdJudge.cs, Assets/Scripts/Value/SensorData.cs, Assets/Scripts/Value/Statistics.cs
#94
SensorData.datas関連の型をfloatに変更
=> センサーデータの型をfloatに変更

Assets/Scenes/GsrSensorScene.unity, Assets/Scripts/GSRScene/Authenticity.cs
=> #97  judge gsr sensor point

Assets/Scenes/Co2SensorScene.unity, Assets/Scripts/CO2Scene/Spawner.cs, Assets/Scripts/CO2Scene/UI/CO2InfoTextUI.cs, Node-RED/flows.json
#104 
二酸化炭素の SensorData.Name を `CO2 -> co2` に変更しました
Node-RED\flows.json をNode-REDに読み込んで、
Azure Storage の情報を入力すると、対応したフローが使用できます。
=> 二酸化炭素の SensorData.Name を `CO2 -> co2`
